image:
  repository: robachmann/netatmo-exporter
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

serviceMonitor:
  create: true
  jobLabel: netatmo-exporter

netatmo: {}

resources:
  requests:
    cpu: 50m
    memory: 512Mi
  limits:
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
