apiVersion: v1
kind: Secret
metadata:
  name: netatmo-exporter-secret
type: Opaque
stringData:
  NETATMO_CLIENT_ID: {{ required "Client ID" .Values.netatmo.clientId | quote }}
  NETATMO_CLIENT_SECRET: {{ required "Client Secret" .Values.netatmo.clientSecret | quote }}
  NETATMO_REFRESH_TOKEN: {{ required "Refresh Token" .Values.netatmo.refreshToken | quote }}
