{{- if .Values.serviceMonitor.create -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: netatmo-exporter
  labels:
    release: prometheus
spec:
  jobLabel: {{ .Values.serviceMonitor.jobLabel }}
  selector:
    matchLabels:
      {{- include "netatmo-exporter.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http-metrics
      interval: 2m
      path: /metrics
{{- end }}