apiVersion: v1
kind: Service
metadata:
  name: {{ include "netatmo-exporter.fullname" . }}
  labels:
    {{- include "netatmo-exporter.labels" . | nindent 4 }}
  annotations:
    alpha.monitoring.coreos.com/non-namespaced: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "netatmo-exporter.selectorLabels" . | nindent 4 }}
